//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPSLSGAMEver4.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPSLSGAMEver4.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an item: \nPaper - P\nScissor - S\nRock - R\nLizard - L\nSpock -V\n.
        /// </summary>
        public static string gameAvailableItems {
            get {
                return ResourceManager.GetString("gameAvailableItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both identities are equal\n.
        /// </summary>
        public static string gameItemsEqualMessage {
            get {
                return ResourceManager.GetString("gameItemsEqualMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Game rules: \nScissors cuts Paper\nPaper covers Rock\nRock crushes Lizard\nLizard poisons Spock\nSpock smashes Scissors\nScissors decapitates Lizard\nLizard eats Paper\nPaper disproves Spock\nSpock vaporizes Rock\nRock crushes Scissors\n.
        /// </summary>
        public static string gameRulesMessage {
            get {
                return ResourceManager.GetString("gameRulesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameResult.txt.
        /// </summary>
        public static string gameSavedDataFileName {
            get {
                return ResourceManager.GetString("gameSavedDataFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPSLS GAME.
        /// </summary>
        public static string gameTitle {
            get {
                return ResourceManager.GetString("gameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the RPSLS Game\nRock, Paper, Scissor, Lizard, Spock\nIf you need to read the game rules hit the H key\nHit the E key to start the game or hit the Q key to quit the game\n&quot;.
        /// </summary>
        public static string gameWelcomeMessage {
            get {
                return ResourceManager.GetString("gameWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nThe machine choosed:.
        /// </summary>
        public static string machineChoosedOtionMessage {
            get {
                return ResourceManager.GetString("machineChoosedOtionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nMachine point:.
        /// </summary>
        public static string machinePointMessage {
            get {
                return ResourceManager.GetString("machinePointMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your name: .
        /// </summary>
        public static string playerAddNameMessage {
            get {
                return ResourceManager.GetString("playerAddNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nYou are choosed:.
        /// </summary>
        public static string playerChoosedOptionMessage {
            get {
                return ResourceManager.GetString("playerChoosedOptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nIf you want a new game hit the E key \nIf you want to quit hit the Q key\n.
        /// </summary>
        public static string playerGameFinalizeNavigationMessage {
            get {
                return ResourceManager.GetString("playerGameFinalizeNavigationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to go back to the main screen hit the B key\n If you want to quit the game hit the Q key\n.
        /// </summary>
        public static string playerGameRulesNavigationMessage {
            get {
                return ResourceManager.GetString("playerGameRulesNavigationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nIf you want to save the result hit the C key\nIf you want to exit the game without save hit the Q key\n.
        /// </summary>
        public static string playerGameSaveResultNavigationMessage {
            get {
                return ResourceManager.GetString("playerGameSaveResultNavigationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nPlease hit a valid key: \n.
        /// </summary>
        public static string playerHitValidKeyMessage {
            get {
                return ResourceManager.GetString("playerHitValidKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are LOSE! :(\nThe winner is:.
        /// </summary>
        public static string playerLoseMessage {
            get {
                return ResourceManager.GetString("playerLoseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nPlayer name:.
        /// </summary>
        public static string playerNameMessage {
            get {
                return ResourceManager.GetString("playerNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nPlayer point:.
        /// </summary>
        public static string playerPointMessage {
            get {
                return ResourceManager.GetString("playerPointMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nWait for player input: .
        /// </summary>
        public static string playerWaitForInputMessage {
            get {
                return ResourceManager.GetString("playerWaitForInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are WIN! :)\nThe winner is:.
        /// </summary>
        public static string playerWinMessage {
            get {
                return ResourceManager.GetString("playerWinMessage", resourceCulture);
            }
        }
    }
}
